name: Administration
on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  unit:
    name: Jest
    uses: shopware/github-actions/.github/workflows/admin-jest.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
  lint:
    name: ESLint
    uses: shopware/github-actions/.github/workflows/admin-eslint.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
