name: Administration
on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Setup extension
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: SwagExtensionStore
          shopwareVersion: trunk
          install-admin: true

      - uses: shopware/github-actions/admin-jest@main
        with:
          extensionName: SwagExtensionStore
          uploadCoverage: 'true'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/eslint@main
        with:
          extensionName: SwagExtensionStore
          shopwareVersion: trunk
