name: Build
on:
  pull_request:
  push:
    branches:
      - trunk
jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/build-zip@main
        with:
          extensionName: ${{ github.event.repository.name }}
