name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - 6.4.x
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  cs:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-cs-fixer:3.63.2, cs2pr

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix . --dry-run --format=checkstyle | cs2pr

  # does not out of the box run with 6.4
  # phpstan:
  #   uses: shopware/github-actions/.github/workflows/phpstan.yml@main
  #   with:
  #     extensionName: ${{ github.event.repository.name }}
  #     shopwareVersion: 6.4

  phpunit:
    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
    with:
      extensionName: ${{ github.event.repository.name }}
      shopwareVersion: 6.4
      uploadCoverage: true
    secrets:
      codecovToken: ${{ secrets.CODECOV_TOKEN }}


