name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - 'phpstan.neon.dist'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - trunk
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  cs:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/cs-fixer@main
        with:
          rules: ''

  phpstan:
    name: Static Analyse
    runs-on: ubuntu-latest
    steps:
      - name: Setup extension
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: SwagExtensionStore
          shopwareVersion: trunk
          install: true

      - uses: shopware/github-actions/phpstan@main
        with:
          extensionName: SwagExtensionStore

  phpunit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup extension
        uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: SwagExtensionStore
          shopwareVersion: trunk

      - uses: shopware/github-actions/phpunit@main
        with:
          extensionName: SwagExtensionStore
          uploadCoverage: 'true'
          filterName: swagextensionstore-testsuite
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
