name: Release to Store
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/store-release@main
        with:
          extensionName: ${{ github.event.repository.name }}
          accountUser: ${{ secrets.SHOPWARE_ACCOUNT_USER }}
          accountPassword: ${{ secrets.SHOPWARE_ACCOUNT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}
